### ISSUE TITLE
unshard vs merge

### ISSUE THREAD

**Issue by harksin** [liquidm/druid-dumbo#8]
hi, 

documentation expose "unshard" mode. ` -m, --mode MODE                  mode to perform (verify, compact, unshard)`
but there is no mention of it in cli code  https://github.com/liquidm/druid-dumbo/blob/master/lib/dumbo/cli.rb#L31-L58

the feature "unshard" has been removed ? or just rename has "merge" ? 

thanks by advance

**Comment by sixtus** [comment]
Looks like I missed that. Yes merge has been removed, but not from the read me. The current version is designed for druid 0.17 and there is no difference between compact and unshard, so it got dropped.
